#ifndef shogi_core_bindings_h
#define shogi_core_bindings_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


#if !defined(DEFINE_STD)
void __bzero(uint8_t *s, size_t n);
#endif

#if !defined(DEFINE_STD)
int32_t memcmp(const uint8_t *s1, const uint8_t *s2, size_t n);
#endif

#if !defined(DEFINE_STD)
uint8_t *memcpy(uint8_t *dest, const uint8_t *src, size_t n);
#endif

#if !defined(DEFINE_STD)
uint8_t *memset(uint8_t *b, int32_t c, size_t n);
#endif

#endif /* shogi_core_bindings_h */
