#ifndef shogi_core_bindings_h
#define shogi_core_bindings_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


/**
 * Checks if the normal move is legal.
 *
 * `piece` is given as a hint and `position.piece_at(from) == Some(piece)` must hold.
 */
bool legality_normal_check(const PartialPosition *position, Piece piece, Square from, Square to);

#endif /* shogi_core_bindings_h */
