#ifndef shogi_official_kifu_bindings_h
#define shogi_official_kifu_bindings_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


#endif /* shogi_official_kifu_bindings_h */
